import { parseYaml, validate } from '@flui-cloud/spec';
import { generateSpec, scalar } from '../src/spec/spec-generate';
import { FRAMEWORK_TEMPLATES, findTemplate } from '../src/spec/template-registry';

const versions = { spec: '0.8.1', vops: '0.1.1' };

describe('spec generate', () => {
  it('produces a manifest flui-spec accepts, for every bundled template', () => {
    for (const template of FRAMEWORK_TEMPLATES) {
      const { yaml } = generateSpec(template, { name: 'my-app' }, versions);
      const result = validate(parseYaml(yaml));
      expect({ id: template.id, errors: result.errors }).toEqual({ id: template.id, errors: [] });
      expect(result.valid).toBe(true);
    }
  });

  it('is deterministic — the same inputs produce the same bytes', () => {
    const t = findTemplate('nestjs-11')!;
    const a = generateSpec(t, { name: 'api', env: { NODE_ENV: 'production' } }, versions);
    const b = generateSpec(t, { name: 'api', env: { NODE_ENV: 'production' } }, versions);
    expect(a.yaml).toBe(b.yaml);
  });

  it('carries the template port and health path through by default, and honours overrides', () => {
    const t = findTemplate('spring-boot-3')!;
    const base = parseYaml(generateSpec(t, { name: 'svc' }, versions).yaml) as any;
    expect(base.deploy.port).toBe(8080);
    expect(base.deploy.healthcheck.path).toBe('/actuator/health');

    const custom = parseYaml(generateSpec(t, { name: 'svc', port: 9000, healthPath: '/ready' }, versions).yaml) as any;
    expect(custom.deploy.port).toBe(9000);
    expect(custom.deploy.healthcheck).toEqual({ path: '/ready', port: 9000 });
  });

  it('declares a generated secret without ever writing a value', () => {
    const t = findTemplate('generic')!;
    const { yaml } = generateSpec(t, { name: 'app', generatedSecrets: ['SESSION_SECRET'] }, versions);
    const doc = parseYaml(yaml) as any;
    expect(doc.deploy.env.SESSION_SECRET.valueFrom).toEqual({ generate: 'secret', length: 32, format: 'base64url' });
    expect(yaml).not.toMatch(/^\s*SESSION_SECRET: .+$/m);
    expect(validate(doc).valid).toBe(true);
  });

  it('records provenance in a comment, since the schema rejects extra root keys', () => {
    const t = findTemplate('nextjs-16')!;
    const { yaml, provenance } = generateSpec(t, { name: 'shop' }, versions);
    expect(yaml.startsWith('# Generated by vops 0.1.1 from template nextjs-16@1.0.0')).toBe(true);
    expect(provenance).toEqual({ templateId: 'nextjs-16', templateVersion: '1.0.0', specVersion: '0.8.1', vopsVersion: '0.1.1' });
    expect(validate(parseYaml(yaml)).valid).toBe(true);
  });

  it('refuses a name that is not a valid handle', () => {
    const t = findTemplate('generic')!;
    expect(() => generateSpec(t, { name: 'My App' }, versions)).toThrow(/Invalid --name/);
  });

  it('flags the decisions the caller still owns', () => {
    const t = findTemplate('django-5')!;
    const { todo } = generateSpec(t, { name: 'site' }, versions);
    expect(todo.join('\n')).toMatch(/deploy\.port defaults to 8000/);
    expect(todo.join('\n')).toMatch(/No hostname is pinned/);
    expect(todo.join('\n')).toMatch(/ALLOWED_HOSTS/);
  });
});

describe('yaml scalar quoting', () => {
  it('quotes anything YAML would re-type on the way back in', () => {
    expect(scalar('production')).toBe('production');
    expect(scalar('/api/health')).toBe('/api/health');
    expect(scalar('yes')).toBe('"yes"');
    expect(scalar('on')).toBe('"on"');
    expect(scalar('1.10')).toBe('"1.10"');
    expect(scalar('null')).toBe('"null"');
    expect(scalar('a: b')).toBe('"a: b"');
    expect(scalar('say "hi"')).toBe('"say \\"hi\\""');
  });
});
