sonar.projectKey=FluiVops
sonar.projectName=Flui Vops
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=lib/**,coverage/**,docs/**,src/ui/assets/**,src/ui/world.geo.json,test/fixtures/**

sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
