kind: Application
apiVersion: flui.cloud/v1beta1

metadata:
  name: example

build:
  strategy: dockerfile
  dockerfile: "./Dockerfile"

deploy:
  port: 3000
  exposure: internal
  healthcheck:
    path: /health
    port: 3000
