import { FrameworkTemplate } from './template-registry';

/** Deterministic `flui.yaml` generation from a framework template — byte-identical for identical
 * inputs (the timestamp lives in `.vops/project.json`, not the manifest, so re-generating produces
 * no diff). Provenance is a YAML comment since the Application schema forbids extra root keys. */

export interface GenerateParams {
  /** metadata.name — the app handle. Required; everything else falls back to the template. */
  name: string;
  port?: number;
  healthPath?: string;
  dockerfile?: string;
  /** Build context relative to the repository root (default: the root itself). */
  context?: string;
  /** Docker build ARGs — baked into the image, so never a secret. */
  buildArgs?: Record<string, string>;
  /** Literal runtime env. Secret VALUES never belong here (spec §9.2). */
  env?: Record<string, string>;
  /** Env names to be filled from a Podman secret generated on the host. */
  generatedSecrets?: string[];
  volumes?: Array<{ name: string; mountPath: string }>;
  /** Explicit FQDN to expose on. Absent = decided at deploy time (`--domain`). */
  fqdn?: string;
  exposure?: 'public' | 'internal';
  startCommand?: string;
}

export interface Provenance {
  templateId: string;
  templateVersion: string;
  specVersion: string;
  vopsVersion: string;
}

export interface GeneratedSpec {
  yaml: string;
  provenance: Provenance;
  /** Fields the caller still has to decide — surfaced as envelope warnings. */
  todo: string[];
}

const API_VERSION = 'flui.cloud/v1beta1';

export function generateSpec(
  template: FrameworkTemplate,
  params: GenerateParams,
  versions: { spec: string; vops: string },
): GeneratedSpec {
  const name = params.name.trim();
  if (!/^[a-z0-9][a-z0-9-]{0,62}$/.test(name)) {
    throw new Error(`Invalid --name '${params.name}' — lowercase letters, digits and dashes only, starting with a letter or digit.`);
  }
  const port = params.port ?? template.port;
  const healthPath = params.healthPath ?? template.healthPath;
  const provenance: Provenance = {
    templateId: template.id,
    templateVersion: template.version,
    specVersion: versions.spec,
    vopsVersion: versions.vops,
  };

  const lines = [
    ...header(template, provenance),
    'kind: Application',
    `apiVersion: ${API_VERSION}`,
    '',
    'metadata:',
    `  name: ${scalar(name)}`,
    '',
    'build:',
    '  strategy: dockerfile',
    `  dockerfile: ${scalar(params.dockerfile ?? template.dockerfile)}`,
    ...(params.context ? [`  context: ${scalar(params.context)}`] : []),
    ...mapBlock('args', params.buildArgs, '  '),
    '',
    'deploy:',
    `  port: ${port}`,
    `  exposure: ${params.exposure ?? 'public'}`,
    '  healthcheck:',
    `    path: ${scalar(healthPath)}`,
    `    port: ${port}`,
    ...(params.startCommand ? [`  startCommand: ${scalar(params.startCommand)}`] : []),
    ...domainBlock(params.fqdn),
    ...envBlock(params),
    ...volumeBlock(params.volumes),
  ];

  return { yaml: `${lines.join('\n').replaceAll(/\n{3,}/g, '\n\n').trimEnd()}\n`, provenance, todo: todos(template, params) };
}

function header(t: FrameworkTemplate, p: Provenance): string[] {
  return [
    `# Generated by vops ${p.vopsVersion} from template ${p.templateId}@${p.templateVersion}`,
    `# Template source: ${t.sourceRepo}`,
    `# flui-spec: ${p.specVersion} · validate with: vops spec validate flui.yaml`,
    '# Secret VALUES never belong in this file — declare them and pass them at deploy.',
    '',
  ];
}

/** `deploy.domain` toggles only. The hostname itself is a deploy-time input
 * unless the caller pinned one, so the same manifest works on any host. */
function domainBlock(fqdn?: string): string[] {
  return [
    '  domain:',
    '    auto: true',
    '    tls: true',
    ...(fqdn ? [`    fqdn: ${scalar(fqdn)}`] : []),
    '    certChallenge: http-01',
    '    certificateProvider: lets-encrypt',
  ];
}

function envBlock(params: GenerateParams): string[] {
  const literal = Object.entries(params.env ?? {});
  const generated = params.generatedSecrets ?? [];
  if (!literal.length && !generated.length) return [];
  return [
    '  env:',
    ...literal.map(([k, v]) => `    ${key(k)}: ${scalar(v)}`),
    ...generated.flatMap((k) => [
      `    ${key(k)}:`,
      '      valueFrom:',
      '        generate: secret',
      '        length: 32',
      '        format: base64url',
    ]),
  ];
}

function volumeBlock(volumes?: Array<{ name: string; mountPath: string }>): string[] {
  if (!volumes?.length) return [];
  return [
    '  volumes:',
    ...volumes.flatMap((v) => [`    - name: ${scalar(v.name)}`, `      mountPath: ${scalar(v.mountPath)}`]),
  ];
}

function mapBlock(label: string, map: Record<string, string> | undefined, indent: string): string[] {
  const entries = Object.entries(map ?? {});
  if (!entries.length) return [];
  return [`${indent}${label}:`, ...entries.map(([k, v]) => `${indent}  ${key(k)}: ${scalar(v)}`)];
}

/** What the agent still has to decide — the honest gaps in a generated base. */
function todos(t: FrameworkTemplate, p: GenerateParams): string[] {
  return [
    ...(p.port === undefined ? [`deploy.port defaults to ${t.port} from the template — confirm it against the repository.`] : []),
    ...(p.healthPath === undefined
      ? [`deploy.healthcheck.path defaults to ${t.healthPath} — the endpoint must exist, or the deploy rolls back on the smoke test.`]
      : []),
    ...(p.fqdn === undefined ? ['No hostname is pinned — pass --domain at deploy time, or set deploy.domain.fqdn.'] : []),
    ...t.limitations,
  ];
}

/** A YAML mapping key: bare when it is a plain identifier, quoted otherwise. */
function key(k: string): string {
  return /^[A-Za-z_][A-Za-z0-9_.-]*$/.test(k) ? k : quote(k);
}

/** A YAML scalar: anything readable as a number/boolean/null, or carrying YAML punctuation, gets
 * quoted — an unquoted `on` or `1.10` changes type on the way back in. */
export function scalar(value: string): string {
  const v = String(value);
  // A colon is fine inside `ghcr.io/x:tag` or a URL, but `a: b` unquoted is a
  // nested mapping — and a trailing colon opens one.
  const opensMapping = v.includes(': ') || v.endsWith(':');
  const safe = /^[A-Za-z0-9/][A-Za-z0-9 _./:@+-]*$/.test(v) && !opensMapping;
  return safe && !ambiguous(v) ? v : quote(v);
}

/** YAML 1.1 booleans/null, and anything that reads as a number. */
const YAML_KEYWORDS = new Set(['y', 'yes', 'n', 'no', 'true', 'false', 'on', 'off', 'null', '~', '']);
const NUMERIC = /^[-+]?\d[\d_]*(\.\d*)?([eE][-+]?\d+)?$/;

function ambiguous(v: string): boolean {
  return YAML_KEYWORDS.has(v.toLowerCase()) || NUMERIC.test(v) || /^0[xXoObB]/.test(v);
}

function quote(v: string): string {
  const escaped = v
    .replaceAll('\\', String.raw`\\`)
    .replaceAll('"', String.raw`\"`)
    .replaceAll('\n', String.raw`\n`);
  return `"${escaped}"`;
}
